// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"product-api/models"
)

// AddProductReader is a Reader for the AddProduct structure.
type AddProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddProductOK creates a AddProductOK with default headers values
func NewAddProductOK() *AddProductOK {
	return &AddProductOK{}
}

/*
AddProductOK describes a response with status code 200, with default header values.

AddProductOK add product o k
*/
type AddProductOK struct {
	Payload *models.Product
}

// IsSuccess returns true when this add product o k response has a 2xx status code
func (o *AddProductOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add product o k response has a 3xx status code
func (o *AddProductOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add product o k response has a 4xx status code
func (o *AddProductOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add product o k response has a 5xx status code
func (o *AddProductOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add product o k response a status code equal to that given
func (o *AddProductOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the add product o k response
func (o *AddProductOK) Code() int {
	return 200
}

func (o *AddProductOK) Error() string {
	return fmt.Sprintf("[POST /product][%d] addProductOK  %+v", 200, o.Payload)
}

func (o *AddProductOK) String() string {
	return fmt.Sprintf("[POST /product][%d] addProductOK  %+v", 200, o.Payload)
}

func (o *AddProductOK) GetPayload() *models.Product {
	return o.Payload
}

func (o *AddProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Product)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
